# Generated by Django 5.2.15 on 2026-07-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='image',
        ),
    ]
