# Generated by Django 5.2.16 on 2026-08-05 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_data',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.customer'),
            preserve_default=False,
        ),
    ]
