# Generated by Django 5.2.16 on 2026-08-06 00:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_data_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='Order_data_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
