# Generated by Django 5.2.16 on 2026-08-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_data_order_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_data',
            name='Order_data_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
